function J = hex_jacobian(x,y,z,xi,eta,zeta)

J = zeros(3,3);

J(1,1) = ( x(2) - x(1) )*(1-eta).*(1-zeta) ...
       + ( x(4) - x(3) )*(  eta).*(1-zeta) ...
       + ( x(6) - x(5) )*(1-eta).*(  zeta) ...
       + ( x(8) - x(7) )*(  eta).*(  zeta);
J(2,1) = ( y(2) - y(1) )*(1-eta).*(1-zeta) ...
       + ( y(4) - y(3) )*(  eta).*(1-zeta) ...
       + ( y(6) - y(5) )*(1-eta).*(  zeta) ...
       + ( y(8) - y(7) )*(  eta).*(  zeta);
J(3,1) = ( z(2) - z(1) )*(1-eta).*(1-zeta) ...
       + ( z(4) - z(3) )*(  eta).*(1-zeta) ...
       + ( z(6) - z(5) )*(1-eta).*(  zeta) ...
       + ( z(8) - z(7) )*(  eta).*(  zeta);

J(1,2) = ( x(3) - x(1) )*(1-xi).*(1-zeta) ...
       + ( x(4) - x(2) )*(  xi).*(1-zeta) ...
       + ( x(7) - x(5) )*(1-xi).*(  zeta) ...
       + ( x(8) - x(6) )*(  xi).*(  zeta);
J(2,2) = ( y(3) - y(1) )*(1-xi).*(1-zeta) ...
       + ( y(4) - y(2) )*(  xi).*(1-zeta) ...
       + ( y(7) - y(5) )*(1-xi).*(  zeta) ...
       + ( y(8) - y(6) )*(  xi).*(  zeta);
J(3,2) = ( z(3) - z(1) )*(1-xi).*(1-zeta) ...
       + ( z(4) - z(2) )*(  xi).*(1-zeta) ...
       + ( z(7) - z(5) )*(1-xi).*(  zeta) ...
       + ( z(8) - z(6) )*(  xi).*(  zeta);

J(1,3) = ( x(5) - x(1) )*(1-xi).*(1-eta) ...
       + ( x(6) - x(2) )*(  xi).*(1-eta) ...
       + ( x(7) - x(3) )*(1-xi).*(  eta) ...
       + ( x(8) - x(4) )*(  xi).*(  eta);
J(2,3) = ( y(5) - y(1) )*(1-xi).*(1-eta) ...
       + ( y(6) - y(2) )*(  xi).*(1-eta) ...
       + ( y(7) - y(3) )*(1-xi).*(  eta) ...
       + ( y(8) - y(4) )*(  xi).*(  eta);
J(3,3) = ( z(5) - z(1) )*(1-xi).*(1-eta) ...
       + ( z(6) - z(2) )*(  xi).*(1-eta) ...
       + ( z(7) - z(3) )*(1-xi).*(  eta) ...
       + ( z(8) - z(4) )*(  xi).*(  eta);

J2 = hex_jacobian_verbose(x,y,z,xi,eta,zeta);
e = max( abs(J-J2),[],"all");
end


function J = hex_jacobian_verbose(x,y,z,xi,eta,zeta)

J = zeros(3,3);
v1 = [x(1),y(1),z(1)];
v2 = [x(2),y(2),z(2)];
v3 = [x(3),y(3),z(3)];
v4 = [x(4),y(4),z(4)];
v5 = [x(5),y(5),z(5)];
v6 = [x(6),y(6),z(6)];
v7 = [x(7),y(7),z(7)];
v8 = [x(8),y(8),z(8)];
% P1 = (1-xi).*(1-eta).*(1-zeta);
% P2 = (  xi).*(1-eta).*(1-zeta);
% P3 = (1-xi).*(  eta).*(1-zeta);
% P4 = (  xi).*(  eta).*(1-zeta);
% P5 = (1-xi).*(1-eta).*(  zeta);
% P6 = (  xi).*(1-eta).*(  zeta);
% P7 = (1-xi).*(  eta).*(  zeta);
% P8 = (  xi).*(  eta).*(  zeta);

dP1dxi = -(1-eta).*(1-zeta);
dP2dxi =  (1-eta).*(1-zeta); % == -dP1dxi
dP3dxi = -(  eta).*(1-zeta);
dP4dxi =  (  eta).*(1-zeta); % == -dP3dxi
dP5dxi = -(1-eta).*(  zeta);
dP6dxi =  (1-eta).*(  zeta); % == -dP5dxi
dP7dxi = -(  eta).*(  zeta);
dP8dxi =  (  eta).*(  zeta); % == -dP7dxi

dP1deta = -(1-xi).*(1-zeta);
dP2deta = -(  xi).*(1-zeta);
dP3deta =  (1-xi).*(1-zeta); % == -dP1deta
dP4deta =  (  xi).*(1-zeta); % == -dP2deta
dP5deta = -(1-xi).*(  zeta);
dP6deta = -(  xi).*(  zeta);
dP7deta =  (1-xi).*(  zeta); % == -dP5deta
dP8deta =  (  xi).*(  zeta); % == -dP6deta

dP1dzeta = -(1-xi).*(1-eta);
dP2dzeta = -(  xi).*(1-eta);
dP3dzeta = -(1-xi).*(  eta);
dP4dzeta = -(  xi).*(  eta);
dP5dzeta =  (1-xi).*(1-eta); % == -dP1dzeta
dP6dzeta =  (  xi).*(1-eta); % == -dP2dzeta
dP7dzeta =  (1-xi).*(  eta); % == -dP3dzeta
dP8dzeta =  (  xi).*(  eta); % == -dP4dzeta

J(1,1) = v1(1)*dP1dxi ...
       + v2(1)*dP2dxi ...
       + v3(1)*dP3dxi ...
       + v4(1)*dP4dxi ...
       + v5(1)*dP5dxi ...
       + v6(1)*dP6dxi ...
       + v7(1)*dP7dxi ...
       + v8(1)*dP8dxi;

J(2,1) = v1(2)*dP1dxi ...
       + v2(2)*dP2dxi ...
       + v3(2)*dP3dxi ...
       + v4(2)*dP4dxi ...
       + v5(2)*dP5dxi ...
       + v6(2)*dP6dxi ...
       + v7(2)*dP7dxi ...
       + v8(2)*dP8dxi;

J(3,1) = v1(3)*dP1dxi ...
       + v2(3)*dP2dxi ...
       + v3(3)*dP3dxi ...
       + v4(3)*dP4dxi ...
       + v5(3)*dP5dxi ...
       + v6(3)*dP6dxi ...
       + v7(3)*dP7dxi ...
       + v8(3)*dP8dxi;

J(1,2) = v1(1)*dP1deta ...
       + v2(1)*dP2deta ...
       + v3(1)*dP3deta ...
       + v4(1)*dP4deta ...
       + v5(1)*dP5deta ...
       + v6(1)*dP6deta ...
       + v7(1)*dP7deta ...
       + v8(1)*dP8deta;

J(2,2) = v1(2)*dP1deta ...
       + v2(2)*dP2deta ...
       + v3(2)*dP3deta ...
       + v4(2)*dP4deta ...
       + v5(2)*dP5deta ...
       + v6(2)*dP6deta ...
       + v7(2)*dP7deta ...
       + v8(2)*dP8deta;

J(3,2) = v1(3)*dP1deta ...
       + v2(3)*dP2deta ...
       + v3(3)*dP3deta ...
       + v4(3)*dP4deta ...
       + v5(3)*dP5deta ...
       + v6(3)*dP6deta ...
       + v7(3)*dP7deta ...
       + v8(3)*dP8deta;

J(1,3) = v1(1)*dP1dzeta ...
       + v2(1)*dP2dzeta ...
       + v3(1)*dP3dzeta ...
       + v4(1)*dP4dzeta ...
       + v5(1)*dP5dzeta ...
       + v6(1)*dP6dzeta ...
       + v7(1)*dP7dzeta ...
       + v8(1)*dP8dzeta;

J(2,3) = v1(2)*dP1dzeta ...
       + v2(2)*dP2dzeta ...
       + v3(2)*dP3dzeta ...
       + v4(2)*dP4dzeta ...
       + v5(2)*dP5dzeta ...
       + v6(2)*dP6dzeta ...
       + v7(2)*dP7dzeta ...
       + v8(2)*dP8dzeta;

J(3,3) = v1(3)*dP1dzeta ...
       + v2(3)*dP2dzeta ...
       + v3(3)*dP3dzeta ...
       + v4(3)*dP4dzeta ...
       + v5(3)*dP5dzeta ...
       + v6(3)*dP6dzeta ...
       + v7(3)*dP7dzeta ...
       + v8(3)*dP8dzeta;
end