function rho = dens_mms(x,y,z,t,in5,l,c,mu,gamma,PrL)
%DENS_MMS
%    RHO = DENS_MMS(X,Y,Z,T,IN5,L,C,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Jul-2025 18:39:01

a10_1 = in5(10);
a11_1 = in5(11);
a12_1 = in5(12);
a13_1 = in5(13);
a14_1 = in5(14);
a15_1 = in5(15);
a16_1 = in5(16);
a17_1 = in5(17);
a18_1 = in5(18);
a19_1 = in5(19);
a20_1 = in5(20);
a21_1 = in5(21);
a22_1 = in5(22);
a1_1 = in5(1);
a2_1 = in5(2);
a3_1 = in5(3);
a4_1 = in5(4);
a5_1 = in5(5);
a6_1 = in5(6);
a7_1 = in5(7);
a8_1 = in5(8);
a9_1 = in5(9);
t2 = 1.0./l;
t3 = t2.^2;
rho = a1_1+a2_1.*sin(pi.*(a4_1+a3_1.*t2.*x))+a5_1.*sin(pi.*(a7_1+a6_1.*t2.*y))+a8_1.*sin(pi.*(a10_1+a9_1.*t2.*z))+a20_1.*sin(pi.*(a22_1+a21_1.*c.*t.*t2))+a11_1.*sin(pi.*(a13_1+a12_1.*t3.*x.*y))+a17_1.*sin(pi.*(a19_1+a18_1.*t3.*x.*z))+a14_1.*sin(pi.*(a16_1+a15_1.*t3.*y.*z));
end
