function p = pres_mms(x,y,z,t,in5,l,c,mu,gamma,PrL)
%PRES_MMS
%    P = PRES_MMS(X,Y,Z,T,IN5,L,C,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    29-Jul-2025 18:39:02

a10_5 = in5(98);
a11_5 = in5(99);
a12_5 = in5(100);
a13_5 = in5(101);
a14_5 = in5(102);
a15_5 = in5(103);
a16_5 = in5(104);
a17_5 = in5(105);
a18_5 = in5(106);
a19_5 = in5(107);
a20_5 = in5(108);
a21_5 = in5(109);
a22_5 = in5(110);
a2_5 = in5(90);
a3_5 = in5(91);
a4_5 = in5(92);
a5_5 = in5(93);
a6_5 = in5(94);
a7_5 = in5(95);
a8_5 = in5(96);
a9_5 = in5(97);
t2 = 1.0./l;
t3 = t2.^2;
p = a2_5.*sin(pi.*(a4_5+a3_5.*t2.*x))+a5_5.*sin(pi.*(a7_5+a6_5.*t2.*y))+a8_5.*sin(pi.*(a10_5+a9_5.*t2.*z))+a20_5.*sin(pi.*(a22_5+a21_5.*c.*t.*t2))+a11_5.*sin(pi.*(a13_5+a12_5.*t3.*x.*y))+a17_5.*sin(pi.*(a19_5+a18_5.*t3.*x.*z))+a14_5.*sin(pi.*(a16_5+a15_5.*t3.*y.*z));
end
