function R = generate_rotation_matrix_3D(alpha,beta,gamma)
% rotation matrices - note order and angle convention
Rotx = [         1,          0,          0;...
                 0, cos(gamma),-sin(gamma);...
                 0, sin(gamma), cos(gamma) ];
Roty = [cos(beta),           0, sin(beta);...
                 0,          1,          0;...
       -sin(beta),           0, cos(beta) ];
Rotz = [cos(alpha),-sin(alpha),          0;...
        sin(alpha), cos(alpha),          0;
                 0,          0,          1 ];
R = Rotz*Roty*Rotx;
end