function val = transfinite_surface_interpolate(xi,eta,xi_min,xi_max,eta_min,eta_max)
xi = xi(:);
eta = eta(:).';
val = (1 -  xi).*xi_min(eta) ...
    +       xi .*xi_max(eta) ...
    + (1 - eta).*eta_min(xi)   ...
    +      eta .*eta_max(xi) ...
    - (1 -  xi).* ( (1 - eta).*eta_min(0) + eta.*eta_max(0) ) ...
    -       xi .* ( (1 - eta).*eta_min(1) + eta.*eta_max(1) );

end