function rho = dens_mms(x,y,z,t,mu,gamma,PrL)
%DENS_MMS
%    RHO = DENS_MMS(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:29

rho = (y-sin(x.*pi.*2.0)./2.0e+1).^2+1.0;
end
