function out1 = mass_source(x,y,z,t,mu,gamma,PrL)
%MASS_SOURCE
%    OUT1 = MASS_SOURCE(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

t2 = x.*pi.*2.0;
t3 = cos(t2);
t4 = sin(t2);
t5 = t4./2.0e+1;
t6 = -t5;
out1 = t3.*pi.*(t4./1.0e+1-y.*2.0).*(y+1.0).*(-1.0./1.0e+1)+(t3.*pi.*(t5-y).*(t6+y+1.0))./5.0;
end
