function out1 = uvel_mms(x,y,z,t,mu,gamma,PrL)
%UVEL_MMS
%    OUT1 = UVEL_MMS(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

out1 = y-sin(x.*pi.*2.0)./2.0e+1+1.0;
end
