function out1 = vvel_mms(x,y,z,t,mu,gamma,PrL)
%VVEL_MMS
%    OUT1 = VVEL_MMS(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

out1 = (pi.*cos(x.*pi.*2.0).*(y+1.0))./1.0e+1;
end
