function out1 = xmtm_source(x,y,z,t,mu,gamma,PrL)
%XMTM_SOURCE
%    OUT1 = XMTM_SOURCE(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

t2 = y+1.0;
t3 = x.*pi.*2.0;
t4 = cos(t3);
t5 = sin(t3);
t6 = t5./2.0e+1;
t7 = -t6;
t10 = (t6-y).^2;
t9 = t2+t7;
t11 = t10+1.0;
out1 = (t4.*pi.*(t6-y))./5.0-(mu.*t5.*pi.^2)./5.0+(t2.*t4.*t11.*pi)./1.0e+1-(t4.*t9.*t11.*pi)./1.0e+1+(t4.*t9.^2.*pi.*(t6-y))./5.0-(t2.*t4.*t9.*pi.*(t5./1.0e+1-y.*2.0))./1.0e+1;
end
