function out1 = ymtm_source(x,y,z,t,mu,gamma,PrL)
%YMTM_SOURCE
%    OUT1 = YMTM_SOURCE(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

t2 = pi.^2;
t3 = y.*2.0;
t4 = y+1.0;
t5 = x.*pi.*2.0;
t6 = cos(t5);
t7 = sin(t5);
t8 = t6.^2;
t9 = t7./1.0e+1;
t10 = t7./2.0e+1;
t11 = -t9;
t12 = -t10;
t15 = (t10-y).^2;
t14 = t4+t12;
t16 = t15+1.0;
out1 = t3+t11-(t2.*t4.*t8.*t16)./1.0e+2+(t2.*t4.^2.*t8.*(t3+t11))./1.0e+2+mu.*t4.*t6.*pi.^3.*(2.0./5.0)+(t2.*t8.*t16.*(t3+2.0))./1.0e+2-(t2.*t4.*t7.*t14.*t16)./5.0+(t2.*t4.*t8.*t14.*(t10-y))./5.0e+1;
end
