function out1 = zmtm_source(x,y,z,t,mu,gamma,PrL)
%ZMTM_SOURCE
%    OUT1 = ZMTM_SOURCE(X,Y,Z,T,MU,GAMMA,PrL)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    03-Aug-2026 20:10:30

out1 = 0.0;
end
