function F = transfinite_interpolant(G1,G2,G3,G4)

x1 = G1.x(-1);  y1 = G1.y(-1);
x2 = G1.x( 1);  y2 = G1.y( 1);
x3 = G3.x( 1);  y3 = G3.y( 1);
x4 = G3.x(-1);  y4 = G3.y(-1);

F.x = @(xi,eta) 0.5 * ( (1 - xi ).*G4.x(eta) + (1 +  xi).*G2.x(eta)   ...
                      + (1 - eta).*G1.x(xi)  + (1 + eta).*G3.x(xi)  ) ...
             - 0.25 * ( (1 - xi ).* ( (1 - eta).*x1 + (1 + eta).*x4 ) ...
                      + (1 + xi ).* ( (1 - eta).*x2 + (1 + eta).*x3 ) );
F.y = @(xi,eta) 0.5 * ( (1 - xi ).*G4.y(eta) + (1 + xi ).*G2.y(eta)   ...
                      + (1 - eta).*G1.y(xi)  + (1 + eta).*G3.y(xi)  ) ...
             - 0.25 * ( (1 - xi ).* ( (1 - eta).*y1 + (1 + eta).*y4 ) ...
                      + (1 + xi ).* ( (1 - eta).*y2 + (1 + eta).*y3 ) );

end