function p = pres_svf(x,y,z,gamma,in5,in6)
%PRES_SVF
%    P = PRES_SVF(X,Y,Z,GAMMA,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Jul-2025 12:55:06

inputs1 = in5(1,:);
inputs2 = in5(2,:);
inputs4 = in5(4,:);
ref1 = in6(1,:);
ref2 = in6(2,:);
p = ((inputs2.*(-inputs4.^2.*(gamma./2.0-1.0./2.0).*((inputs1.^2.*1.0./ref1.^2)./(x.^2+y.^2)-1.0)+1.0).^(1.0./(gamma-1.0)))./ref2).^gamma./gamma;
end
