function out1 = vvel_svf(x,y,z,gamma,in5,in6)
%VVEL_SVF
%    OUT1 = VVEL_SVF(X,Y,Z,GAMMA,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Jul-2025 12:55:06

inputs1 = in5(1,:);
inputs2 = in5(2,:);
inputs3 = in5(3,:);
inputs4 = in5(4,:);
ref1 = in6(1,:);
ref2 = in6(2,:);
ref3 = in6(3,:);
out1 = -(inputs1.*inputs4.*x.*(inputs2./ref2).^(gamma./2.0-1.0./2.0).*sqrt((gamma.*inputs3.*1.0./ref3.^2)./inputs2))./(ref1.*(x.^2+y.^2));
end
