function out1 = wvel_svf(x,y,z,gamma,in5,in6)
%WVEL_SVF
%    OUT1 = WVEL_SVF(X,Y,Z,GAMMA,IN5,IN6)

%    This function was generated by the Symbolic Math Toolbox version 9.3.
%    30-Jul-2025 12:55:06

out1 = z;
end
