function GRID = calc_vertex_centroids(GRID)
for n = 1:GRID.nblocks
    GRID.gblock(n) = calc_gblock_vertex_centroids(GRID.gblock(n));
end
end
function gblock = calc_gblock_vertex_centroids(gblock)
I  = 1:gblock.Ncells(1);
J  = 1:gblock.Ncells(2);
K  = 1:gblock.Ncells(3);
if gblock.dim==1
    gblock.grid_vars.cell_c(1,:,:,:) = ...
         0.5*( gblock.x(I  ,:,:) + gblock.x(I+1,:,:) );
    gblock.grid_vars.cell_c(2,:,:,:) = ...
         0.5*( gblock.y(I  ,:,:) + gblock.y(I+1,:,:) );
    gblock.grid_vars.cell_c(3,:,:,:) = ...
         0.5*( gblock.z(I  ,:,:) + gblock.z(I+1,:,:) );
elseif gblock.dim==2
    gblock.grid_vars.cell_c(1,:,:,:) = ...
        0.25*( gblock.x(I  ,J  ,:) + gblock.x(I+1,J  ,:) ...
             + gblock.x(I  ,J+1,:) + gblock.x(I+1,J+1,:) );
    gblock.grid_vars.cell_c(2,:,:,:) = ...
        0.25*( gblock.y(I  ,J  ,:) + gblock.y(I+1,J  ,:) ...
             + gblock.y(I  ,J+1,:) + gblock.y(I+1,J+1,:) );
    gblock.grid_vars.cell_c(3,:,:,:) = ...
        0.25*( gblock.z(I  ,J  ,:) + gblock.z(I+1,J  ,:) ...
             + gblock.z(I  ,J+1,:) + gblock.z(I+1,J+1,:) );
elseif gblock.dim==3
    gblock.grid_vars.cell_c(1,:,:,:) = ...
        0.125*( gblock.x(I  ,J  ,K  ) + gblock.x(I+1,J  ,K  ) ...
              + gblock.x(I  ,J+1,K  ) + gblock.x(I+1,J+1,K  ) ...
              + gblock.x(I  ,J  ,K  ) + gblock.x(I+1,J  ,K+1) ...
              + gblock.x(I  ,J+1,K  ) + gblock.x(I+1,J+1,K+1) );
    gblock.grid_vars.cell_c(2,:,:,:) = ...
        0.125*( gblock.y(I  ,J  ,K  ) + gblock.y(I+1,J  ,K  ) ...
              + gblock.y(I  ,J+1,K  ) + gblock.y(I+1,J+1,K  ) ...
              + gblock.y(I  ,J  ,K  ) + gblock.y(I+1,J  ,K+1) ...
              + gblock.y(I  ,J+1,K  ) + gblock.y(I+1,J+1,K+1) );
    gblock.grid_vars.cell_c(3,:,:,:) = ...
        0.125*( gblock.z(I  ,J  ,K  ) + gblock.z(I+1,J  ,K  ) ...
              + gblock.z(I  ,J+1,K  ) + gblock.z(I+1,J+1,K  ) ...
              + gblock.z(I  ,J  ,K  ) + gblock.z(I+1,J  ,K+1) ...
              + gblock.z(I  ,J+1,K  ) + gblock.z(I+1,J+1,K+1) );
end
end